frame_id: map
route:
- name: START
  x: 3.86
  y: 3.886
  yaw: 3.141592653589793
  action: depart_left
- name: TOP_LIGHT_WAIT
  x: 2.62
  y: 3.886
  yaw: 3.141592653589793
  action: traffic_light_wait
- name: TOP_AFTER_LIGHT
  x: 1.75
  y: 3.886
  yaw: 3.141592653589793
  action: continue_left
- name: LEFT_CORNER
  x: 0.314
  y: 3.886
  yaw: -1.5707963267948966
  action: turn_down
- name: A_LEFT_VIEW
  x: 0.314
  y: 3.25
  yaw: -1.5707963267948966
  action: view_A_left
- name: MIDDLE_LEFT
  x: 0.314
  y: 2.624
  yaw: 0.0
  action: turn_right
- name: A_BOTTOM_B_TOP_VIEW
  x: 1.25
  y: 2.624
  yaw: 0.0
  action: view_A_bottom_and_B_top
- name: CENTER_TURN
  x: 1.994
  y: 2.624
  yaw: -1.5707963267948966
  action: turn_down
- name: B_RIGHT_VIEW
  x: 1.994
  y: 2.0
  yaw: -1.5707963267948966
  action: view_B_right
- name: MID_LIGHT_WAIT
  x: 1.994
  y: 1.86
  yaw: -1.5707963267948966
  action: traffic_light_wait
- name: BOTTOM_TURN
  x: 1.994
  y: 0.312
  yaw: 0.0
  action: turn_right
- name: PARKING_ENTRY
  x: 3.254
  y: 0.312
  yaw: 1.5707963267948966
  action: turn_up
- name: PLATE_1
  x: 3.254
  y: 0.5
  yaw: 1.5707963267948966
  action: read_plate_1
- name: PLATE_2
  x: 3.254
  y: 0.956
  yaw: 1.5707963267948966
  action: read_plate_2
- name: PLATE_3
  x: 3.254
  y: 1.598
  yaw: 1.5707963267948966
  action: read_plate_3
- name: RIGHT_TOP
  x: 3.254
  y: 3.886
  yaw: 0.0
  action: turn_finish
- name: FINISH
  x: 3.86
  y: 3.886
  yaw: 0.0
  action: finish
